//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.20 at 03:58:03 PM IST 
//


package access.management;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppRoleResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppRoleResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isSystemRole" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="updatedBy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="createdAt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="updatedAt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="customAttribute1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute4" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute5" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute6" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute7" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute8" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute9" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customAttribute10" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppRoleResponse", propOrder = {
    "id",
    "name",
    "description",
    "isActive",
    "isSystemRole",
    "createdBy",
    "updatedBy",
    "createdAt",
    "updatedAt",
    "customAttribute1",
    "customAttribute2",
    "customAttribute3",
    "customAttribute4",
    "customAttribute5",
    "customAttribute6",
    "customAttribute7",
    "customAttribute8",
    "customAttribute9",
    "customAttribute10"
})
public class AppRoleResponse {

    protected int id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    protected boolean isActive;
    protected boolean isSystemRole;
    protected int createdBy;
    protected int updatedBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdAt;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedAt;
    @XmlElement(required = true)
    protected String customAttribute1;
    @XmlElement(required = true)
    protected String customAttribute2;
    @XmlElement(required = true)
    protected String customAttribute3;
    @XmlElement(required = true)
    protected String customAttribute4;
    @XmlElement(required = true)
    protected String customAttribute5;
    @XmlElement(required = true)
    protected String customAttribute6;
    @XmlElement(required = true)
    protected String customAttribute7;
    @XmlElement(required = true)
    protected String customAttribute8;
    @XmlElement(required = true)
    protected String customAttribute9;
    @XmlElement(required = true)
    protected String customAttribute10;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isSystemRole property.
     * 
     */
    public boolean isIsSystemRole() {
        return isSystemRole;
    }

    /**
     * Sets the value of the isSystemRole property.
     * 
     */
    public void setIsSystemRole(boolean value) {
        this.isSystemRole = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     */
    public int getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     */
    public void setCreatedBy(int value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     */
    public int getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     */
    public void setUpdatedBy(int value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedAt(XMLGregorianCalendar value) {
        this.createdAt = value;
    }

    /**
     * Gets the value of the updatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the value of the updatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedAt(XMLGregorianCalendar value) {
        this.updatedAt = value;
    }

    /**
     * Gets the value of the customAttribute1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute1() {
        return customAttribute1;
    }

    /**
     * Sets the value of the customAttribute1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute1(String value) {
        this.customAttribute1 = value;
    }

    /**
     * Gets the value of the customAttribute2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute2() {
        return customAttribute2;
    }

    /**
     * Sets the value of the customAttribute2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute2(String value) {
        this.customAttribute2 = value;
    }

    /**
     * Gets the value of the customAttribute3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute3() {
        return customAttribute3;
    }

    /**
     * Sets the value of the customAttribute3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute3(String value) {
        this.customAttribute3 = value;
    }

    /**
     * Gets the value of the customAttribute4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute4() {
        return customAttribute4;
    }

    /**
     * Sets the value of the customAttribute4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute4(String value) {
        this.customAttribute4 = value;
    }

    /**
     * Gets the value of the customAttribute5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute5() {
        return customAttribute5;
    }

    /**
     * Sets the value of the customAttribute5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute5(String value) {
        this.customAttribute5 = value;
    }

    /**
     * Gets the value of the customAttribute6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute6() {
        return customAttribute6;
    }

    /**
     * Sets the value of the customAttribute6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute6(String value) {
        this.customAttribute6 = value;
    }

    /**
     * Gets the value of the customAttribute7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute7() {
        return customAttribute7;
    }

    /**
     * Sets the value of the customAttribute7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute7(String value) {
        this.customAttribute7 = value;
    }

    /**
     * Gets the value of the customAttribute8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute8() {
        return customAttribute8;
    }

    /**
     * Sets the value of the customAttribute8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute8(String value) {
        this.customAttribute8 = value;
    }

    /**
     * Gets the value of the customAttribute9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute9() {
        return customAttribute9;
    }

    /**
     * Sets the value of the customAttribute9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute9(String value) {
        this.customAttribute9 = value;
    }

    /**
     * Gets the value of the customAttribute10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttribute10() {
        return customAttribute10;
    }

    /**
     * Sets the value of the customAttribute10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttribute10(String value) {
        this.customAttribute10 = value;
    }

}
