//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.20 at 03:58:03 PM IST 
//


package access.management;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AppUserGroup" type="{http://access/management}AppUserGroupResponse"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appUserGroup"
})
@XmlRootElement(name = "AppUserGroupPutRequest")
public class AppUserGroupPutRequest {

    @XmlElement(name = "AppUserGroup", required = true)
    protected AppUserGroupResponse appUserGroup;

    /**
     * Gets the value of the appUserGroup property.
     * 
     * @return
     *     possible object is
     *     {@link AppUserGroupResponse }
     *     
     */
    public AppUserGroupResponse getAppUserGroup() {
        return appUserGroup;
    }

    /**
     * Sets the value of the appUserGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppUserGroupResponse }
     *     
     */
    public void setAppUserGroup(AppUserGroupResponse value) {
        this.appUserGroup = value;
    }

}
