//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.20 at 03:58:03 PM IST 
//


package access.management;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the access.management package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: access.management
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppGroupGetAllRequest }
     * 
     */
    public AppGroupGetAllRequest createAppGroupGetAllRequest() {
        return new AppGroupGetAllRequest();
    }

    /**
     * Create an instance of {@link AppGroupGetAllResponse }
     * 
     */
    public AppGroupGetAllResponse createAppGroupGetAllResponse() {
        return new AppGroupGetAllResponse();
    }

    /**
     * Create an instance of {@link AppGroupResponse }
     * 
     */
    public AppGroupResponse createAppGroupResponse() {
        return new AppGroupResponse();
    }

    /**
     * Create an instance of {@link AppGroupGetRequest }
     * 
     */
    public AppGroupGetRequest createAppGroupGetRequest() {
        return new AppGroupGetRequest();
    }

    /**
     * Create an instance of {@link AppGroupGetResponse }
     * 
     */
    public AppGroupGetResponse createAppGroupGetResponse() {
        return new AppGroupGetResponse();
    }

    /**
     * Create an instance of {@link AppGroupDelRequest }
     * 
     */
    public AppGroupDelRequest createAppGroupDelRequest() {
        return new AppGroupDelRequest();
    }

    /**
     * Create an instance of {@link AppGroupDelResponse }
     * 
     */
    public AppGroupDelResponse createAppGroupDelResponse() {
        return new AppGroupDelResponse();
    }

    /**
     * Create an instance of {@link AppGroupPostRequest }
     * 
     */
    public AppGroupPostRequest createAppGroupPostRequest() {
        return new AppGroupPostRequest();
    }

    /**
     * Create an instance of {@link AppGroupPostResponse }
     * 
     */
    public AppGroupPostResponse createAppGroupPostResponse() {
        return new AppGroupPostResponse();
    }

    /**
     * Create an instance of {@link AppGroupPutRequest }
     * 
     */
    public AppGroupPutRequest createAppGroupPutRequest() {
        return new AppGroupPutRequest();
    }

    /**
     * Create an instance of {@link AppGroupPutResponse }
     * 
     */
    public AppGroupPutResponse createAppGroupPutResponse() {
        return new AppGroupPutResponse();
    }

    /**
     * Create an instance of {@link AppRoleGetAllRequest }
     * 
     */
    public AppRoleGetAllRequest createAppRoleGetAllRequest() {
        return new AppRoleGetAllRequest();
    }

    /**
     * Create an instance of {@link AppRoleGetAllResponse }
     * 
     */
    public AppRoleGetAllResponse createAppRoleGetAllResponse() {
        return new AppRoleGetAllResponse();
    }

    /**
     * Create an instance of {@link AppRoleResponse }
     * 
     */
    public AppRoleResponse createAppRoleResponse() {
        return new AppRoleResponse();
    }

    /**
     * Create an instance of {@link AppRoleGetRequest }
     * 
     */
    public AppRoleGetRequest createAppRoleGetRequest() {
        return new AppRoleGetRequest();
    }

    /**
     * Create an instance of {@link AppRoleGetResponse }
     * 
     */
    public AppRoleGetResponse createAppRoleGetResponse() {
        return new AppRoleGetResponse();
    }

    /**
     * Create an instance of {@link AppRoleDelRequest }
     * 
     */
    public AppRoleDelRequest createAppRoleDelRequest() {
        return new AppRoleDelRequest();
    }

    /**
     * Create an instance of {@link AppRoleDelResponse }
     * 
     */
    public AppRoleDelResponse createAppRoleDelResponse() {
        return new AppRoleDelResponse();
    }

    /**
     * Create an instance of {@link AppRolePostRequest }
     * 
     */
    public AppRolePostRequest createAppRolePostRequest() {
        return new AppRolePostRequest();
    }

    /**
     * Create an instance of {@link AppRolePostResponse }
     * 
     */
    public AppRolePostResponse createAppRolePostResponse() {
        return new AppRolePostResponse();
    }

    /**
     * Create an instance of {@link AppRolePutRequest }
     * 
     */
    public AppRolePutRequest createAppRolePutRequest() {
        return new AppRolePutRequest();
    }

    /**
     * Create an instance of {@link AppRolePutResponse }
     * 
     */
    public AppRolePutResponse createAppRolePutResponse() {
        return new AppRolePutResponse();
    }

    /**
     * Create an instance of {@link AppUserGetAllRequest }
     * 
     */
    public AppUserGetAllRequest createAppUserGetAllRequest() {
        return new AppUserGetAllRequest();
    }

    /**
     * Create an instance of {@link AppUserGetAllResponse }
     * 
     */
    public AppUserGetAllResponse createAppUserGetAllResponse() {
        return new AppUserGetAllResponse();
    }

    /**
     * Create an instance of {@link AppUserResponse }
     * 
     */
    public AppUserResponse createAppUserResponse() {
        return new AppUserResponse();
    }

    /**
     * Create an instance of {@link AppUserGetRequest }
     * 
     */
    public AppUserGetRequest createAppUserGetRequest() {
        return new AppUserGetRequest();
    }

    /**
     * Create an instance of {@link AppUserGetResponse }
     * 
     */
    public AppUserGetResponse createAppUserGetResponse() {
        return new AppUserGetResponse();
    }

    /**
     * Create an instance of {@link AppUserDelRequest }
     * 
     */
    public AppUserDelRequest createAppUserDelRequest() {
        return new AppUserDelRequest();
    }

    /**
     * Create an instance of {@link AppUserDelResponse }
     * 
     */
    public AppUserDelResponse createAppUserDelResponse() {
        return new AppUserDelResponse();
    }

    /**
     * Create an instance of {@link AppUserPostRequest }
     * 
     */
    public AppUserPostRequest createAppUserPostRequest() {
        return new AppUserPostRequest();
    }

    /**
     * Create an instance of {@link AppUserPostResponse }
     * 
     */
    public AppUserPostResponse createAppUserPostResponse() {
        return new AppUserPostResponse();
    }

    /**
     * Create an instance of {@link AppUserPutRequest }
     * 
     */
    public AppUserPutRequest createAppUserPutRequest() {
        return new AppUserPutRequest();
    }

    /**
     * Create an instance of {@link AppUserPutResponse }
     * 
     */
    public AppUserPutResponse createAppUserPutResponse() {
        return new AppUserPutResponse();
    }

    /**
     * Create an instance of {@link AppUserGroupGetAllRequest }
     * 
     */
    public AppUserGroupGetAllRequest createAppUserGroupGetAllRequest() {
        return new AppUserGroupGetAllRequest();
    }

    /**
     * Create an instance of {@link AppUserGroupGetAllResponse }
     * 
     */
    public AppUserGroupGetAllResponse createAppUserGroupGetAllResponse() {
        return new AppUserGroupGetAllResponse();
    }

    /**
     * Create an instance of {@link AppUserGroupResponse }
     * 
     */
    public AppUserGroupResponse createAppUserGroupResponse() {
        return new AppUserGroupResponse();
    }

    /**
     * Create an instance of {@link AppUserGroupGetRequest }
     * 
     */
    public AppUserGroupGetRequest createAppUserGroupGetRequest() {
        return new AppUserGroupGetRequest();
    }

    /**
     * Create an instance of {@link AppUserGroupGetResponse }
     * 
     */
    public AppUserGroupGetResponse createAppUserGroupGetResponse() {
        return new AppUserGroupGetResponse();
    }

    /**
     * Create an instance of {@link AppUserGroupDelRequest }
     * 
     */
    public AppUserGroupDelRequest createAppUserGroupDelRequest() {
        return new AppUserGroupDelRequest();
    }

    /**
     * Create an instance of {@link AppUserGroupDelResponse }
     * 
     */
    public AppUserGroupDelResponse createAppUserGroupDelResponse() {
        return new AppUserGroupDelResponse();
    }

    /**
     * Create an instance of {@link AppUserGroupPostRequest }
     * 
     */
    public AppUserGroupPostRequest createAppUserGroupPostRequest() {
        return new AppUserGroupPostRequest();
    }

    /**
     * Create an instance of {@link AppUserGroupPostResponse }
     * 
     */
    public AppUserGroupPostResponse createAppUserGroupPostResponse() {
        return new AppUserGroupPostResponse();
    }

    /**
     * Create an instance of {@link AppUserGroupPutRequest }
     * 
     */
    public AppUserGroupPutRequest createAppUserGroupPutRequest() {
        return new AppUserGroupPutRequest();
    }

    /**
     * Create an instance of {@link AppUserGroupPutResponse }
     * 
     */
    public AppUserGroupPutResponse createAppUserGroupPutResponse() {
        return new AppUserGroupPutResponse();
    }

    /**
     * Create an instance of {@link AppUserRoleGetAllRequest }
     * 
     */
    public AppUserRoleGetAllRequest createAppUserRoleGetAllRequest() {
        return new AppUserRoleGetAllRequest();
    }

    /**
     * Create an instance of {@link AppUserRoleGetAllResponse }
     * 
     */
    public AppUserRoleGetAllResponse createAppUserRoleGetAllResponse() {
        return new AppUserRoleGetAllResponse();
    }

    /**
     * Create an instance of {@link AppUserRoleResponse }
     * 
     */
    public AppUserRoleResponse createAppUserRoleResponse() {
        return new AppUserRoleResponse();
    }

    /**
     * Create an instance of {@link AppUserRoleGetRequest }
     * 
     */
    public AppUserRoleGetRequest createAppUserRoleGetRequest() {
        return new AppUserRoleGetRequest();
    }

    /**
     * Create an instance of {@link AppUserRoleGetResponse }
     * 
     */
    public AppUserRoleGetResponse createAppUserRoleGetResponse() {
        return new AppUserRoleGetResponse();
    }

    /**
     * Create an instance of {@link AppUserRoleDelRequest }
     * 
     */
    public AppUserRoleDelRequest createAppUserRoleDelRequest() {
        return new AppUserRoleDelRequest();
    }

    /**
     * Create an instance of {@link AppUserRoleDelResponse }
     * 
     */
    public AppUserRoleDelResponse createAppUserRoleDelResponse() {
        return new AppUserRoleDelResponse();
    }

    /**
     * Create an instance of {@link AppUserRolePostRequest }
     * 
     */
    public AppUserRolePostRequest createAppUserRolePostRequest() {
        return new AppUserRolePostRequest();
    }

    /**
     * Create an instance of {@link AppUserRolePostResponse }
     * 
     */
    public AppUserRolePostResponse createAppUserRolePostResponse() {
        return new AppUserRolePostResponse();
    }

    /**
     * Create an instance of {@link AppUserRolePutRequest }
     * 
     */
    public AppUserRolePutRequest createAppUserRolePutRequest() {
        return new AppUserRolePutRequest();
    }

    /**
     * Create an instance of {@link AppUserRolePutResponse }
     * 
     */
    public AppUserRolePutResponse createAppUserRolePutResponse() {
        return new AppUserRolePutResponse();
    }

}
